# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99d922052dafab7630b617d749892def4789c6b7f3e362fe3ff716fe2b3eb1f1e6c10ab1792080c0788cc1a216d21a20614e7d8291c19af66399799c361ea01

test:
  secret_key_base: 588bfd7a2aa682577be622216a4b7a6dc7e0359a2ca484d8bc31380a488d395de832fbc0b04b870b76e186d3dbea43af74cde7776a44e74e1194cf4a71517d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
